openapi: 3.0.0
servers:
  - url: http://localhost:8080/api
    description: Client Service API
info:
  description: This API provides integrated user and order information
  version: 1.0.0
  title: Client Service API
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'

tags:
  - name: user-orders
    description: Integrated user and order operations

paths:
  /orders/user/{id}:
    get:
      tags:
        - order
      summary: get the list of orders
      description: send request to orders table and retrieve all orders related one user
      operationId: getOrdersByUserId
      parameters:
        - name: id
          in: path
          required: true
          description: The unique identifier of the user
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Order details retrieved successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderDTO'
        '404':
          description: Order not found.
          content:
            application/json:
              schema:
                $ref: './api.yml#/components/schemas/Response'

components:
  schemas:
    OrderDTO:
      type: object
      properties:
        order_id:
          type: integer
          format: int64
        user_id:
          type: integer
          format: int64
        product_name:
          type: string
        quantity:
          type: integer
          format: int32
        price:
          type: number
          format: decimal
          minimum: 0
      required:
        - order_id
        - product_name
        - quantity
        - price
